"""Turning an evidence bundle into prose — without ever writing a number.

Two narrators, one contract: **emit `{{slot.id}}` references, never digits.**
The verifier enforces it, so a narrator cannot damage correctness — only
readability.

  * `template_narrate` is deterministic and needs no credentials. It is the
    default, and it is what makes the whole system runnable and evaluable with
    zero setup.
  * `llm_narrate` (copilot/planner/llm.py) produces better prose under the same
    constraint. Graceful degradation here means degrading to *less fluent*,
    never to *wrong*.

Warnings are not optional garnish. A premise refutation or a collinearity flag
leads the answer, because burying it would make a technically-true response
practically misleading.

Note on scope: the verifier scans the *narrated* text. Warning strings are
generated by operator code, not by a model, so they are trusted for the same
reason slot values are — nothing sampled from a distribution produced them.
"""

from __future__ import annotations

from copilot.evidence import EvidenceBundle, Severity
from copilot.ir import AnalysisPlan, OpName

__all__ = ["template_narrate", "lead_with_warnings", "format_answer"]


def template_narrate(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    """Deterministic narration. Slot references only."""
    body = _BY_OP.get(plan.op, _generic)(plan, bundle)
    return "\n\n".join(p for p in [lead_with_warnings(bundle), body] if p)


def lead_with_warnings(bundle: EvidenceBundle) -> str:
    """Critical caveats first. A refuted premise is the answer, not a footnote."""
    critical = [w for w in bundle.warnings if w.severity is Severity.CRITICAL]
    return "\n".join(w.message for w in critical)


def _has(bundle: EvidenceBundle, *ids: str) -> bool:
    return all(i in bundle.slots for i in ids)


def _ref(slot_id: str) -> str:
    return f"{{{{{slot_id}}}}}"


# --------------------------------------------------------------------------
# Per-operator templates
# --------------------------------------------------------------------------


def _describe(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    cohorts = [c.name for c in plan.cohorts] or ["all"]
    lines = []
    for cohort in cohorts:
        for metric in plan.metrics:
            base = f"{cohort}.{metric}"
            if not _has(bundle, f"{base}.mean"):
                continue
            label = _label(metric)
            lines.append(
                f"For {cohort} cycles, {label} averages {_ref(f'{base}.mean')} "
                f"(median {_ref(f'{base}.median')}, range {_ref(f'{base}.min')} "
                f"to {_ref(f'{base}.max')}) across {_ref(f'{base}.n')} cycles."
            )
    return "\n".join(lines) or "No matching cycles."


def _rate(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    lines = []
    if _has(bundle, "premise.shape"):
        shape = _ref("premise.shape")
        lines.append(
            f"Across this axis the failure rate is {shape}: the first band is at "
            f"{_ref('premise.first_group_rate')} against {_ref('premise.last_group_rate')} "
            f"at the last."
        )
        if _has(bundle, "premise.low_high_ratio"):
            lines.append(
                f"That is a ratio of {_ref('premise.low_high_ratio')} between the two ends."
            )
    groups = [
        k.rsplit(".", 1)[0]
        for k in bundle.slots
        if k.endswith(".failure_rate") and not k.startswith(("overall", "premise"))
    ]
    for group in groups[:12]:
        lines.append(
            f"{_ref(f'{group}.label')}: {_ref(f'{group}.failure_rate')} "
            f"({_ref(f'{group}.failures')} of {_ref(f'{group}.n')})."
        )
    if _has(bundle, "overall.failure_rate"):
        lines.append(
            f"Overall: {_ref('overall.failure_rate')} "
            f"({_ref('overall.failures')} of {_ref('overall.n')})."
        )
    elif _has(bundle, "all.failure_rate"):
        lines.append(
            f"Overall: {_ref('all.failure_rate')} "
            f"({_ref('all.failures')} of {_ref('all.n')})."
        )
    return "\n".join(lines)


def _compare(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    if len(plan.cohorts) < 2:
        return "Two cohorts are required for a comparison."
    a, b = plan.cohorts[0].name, plan.cohorts[1].name
    lines = [
        f"Comparing {a} ({_ref(f'{a}.n')} cycles) with {b} ({_ref(f'{b}.n')} cycles):"
    ]
    for metric in plan.metrics:
        if not _has(bundle, f"{a}.{metric}.mean"):
            continue
        lines.append(
            f"- {_label(metric)}: {_ref(f'{a}.{metric}.mean')} versus "
            f"{_ref(f'{b}.{metric}.mean')}, a difference of {_ref(f'delta.{metric}')} "
            f"(standardised effect {_ref(f'effect.{metric}.cohens_d')}, "
            f"{_ref(f'effect.{metric}.magnitude')})."
        )
    return "\n".join(lines)


def _root_cause(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    if _has(bundle, "cause.verdict") and _has(bundle, "cycle.udi"):
        return _root_cause_single(bundle)
    return _root_cause_cohort(bundle)


def _root_cause_single(bundle: EvidenceBundle) -> str:
    verdict = bundle.slots["cause.verdict"]
    lines = []
    if verdict.value == "cause_undetermined":
        lines.append(
            f"Cycle {_ref('cycle.udi')} is labelled a failure, but no documented mode "
            f"fires and every margin sits in the normal range "
            f"(worst normalised margin {_ref('cause.worst_normalised_margin')}). "
            "The cause cannot be determined from the published parameters."
        )
    elif verdict.value == "no failure mode triggered":
        lines.append(
            f"Cycle {_ref('cycle.udi')} did not fail, and no mode came close to firing. "
            f"The nearest boundary was {_ref('closest.rule')}, binding on "
            f"{_ref('closest.binding_condition')} with {_ref('closest.margin')} to spare."
        )
    else:
        lines.append(f"Cycle {_ref('cycle.udi')} failed by {_ref('cause.verdict')}.")
        if _has(bundle, "OSF.overstrain_margin_min_nm") and bundle.slots["OSF.fired"].value == "yes":
            lines.append(
                f"Overstrain exceeded its limit by {_ref('OSF.overstrain_margin_min_nm')}; "
                f"at this torque the boundary is crossed at {_ref('OSF.crossing_wear_min')} "
                f"of wear."
            )
        if _has(bundle, "PWF.power_high_margin_w") and bundle.slots["PWF.fired"].value == "yes":
            lines.append(
                f"Power sat outside the usable band (headroom to the ceiling "
                f"{_ref('PWF.power_high_margin_w')}, to the floor "
                f"{_ref('PWF.power_low_margin_w')})."
            )
        if _has(bundle, "HDF.temp_delta_margin_k") and bundle.slots["HDF.fired"].value == "yes":
            lines.append(
                f"Heat dissipation failed: thermal margin {_ref('HDF.temp_delta_margin_k')} "
                f"and speed margin {_ref('HDF.speed_margin_rpm')}, both negative."
            )
    if _has(bundle, "TWF.failure_probability"):
        lines.append(
            f"Tool wear is inside the replacement window, carrying a per-cycle failure "
            f"probability of {_ref('TWF.failure_probability')}. This mode is stochastic, "
            "so it is a probability rather than a prediction."
        )
    return "\n".join(lines)


def _root_cause_cohort(bundle: EvidenceBundle) -> str:
    lines = [
        f"Across {_ref('cohort.n')} cycles there were {_ref('cohort.failures')} failures, "
        f"of which {_ref('explained.deterministic')} are explained exactly by the "
        f"documented rules."
    ]
    for mode in ("HDF", "PWF", "OSF", "TWF"):
        if _has(bundle, f"{mode}.count"):
            lines.append(f"- {mode}: {_ref(f'{mode}.count')} cycles.")
    if _has(bundle, "orphans.count") and bundle.slots["orphans.count"].value:
        lines.append(
            f"{_ref('orphans.count')} failures have no documented mode and are excluded "
            "from attribution."
        )
    if _has(bundle, "multi_mode.count") and bundle.slots["multi_mode.count"].value:
        lines.append(
            f"{_ref('multi_mode.count')} failures fired more than one mode at once, so "
            "the per-mode counts sum to more than the failure total."
        )
    return "\n".join(lines)


def _trend(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    lines = [
        f"Along {_ref('axis.name')} over {_ref('axis.points')} points, the failure rate "
        f"is {_ref('slope.failure_rate.direction')} at {_ref('slope.failure_rate')} per step."
    ]
    # Insertion order is axis order (the query is ORDER BY the axis column).
    # Sorting here would print the buckets in slug order, which is nonsense.
    buckets = [
        k.rsplit(".", 1)[0]
        for k in bundle.slots
        if k.startswith("bucket.") and k.endswith(".failure_rate")
    ]
    for bucket in buckets[:12]:
        lines.append(f"- {_ref(f'{bucket}.label')}: {_ref(f'{bucket}.failure_rate')}")
    if _has(bundle, "changepoint.at"):
        lines.append(
            f"The rate shifts markedly around {_ref('changepoint.at')}, a move of "
            f"{_ref('changepoint.shift')}."
        )
    return "\n".join(lines)


def _drivers(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    n = int(bundle.slots["drivers.considered"].value or 0) if _has(bundle, "drivers.considered") else 0
    lines = [
        f"Ranking {_ref('drivers.considered')} variables by how strongly they separate "
        f"the two groups:"
    ]
    for i in range(1, min(n, 5) + 1):
        lines.append(
            f"{_ref(f'rank{i}.position')}. {_ref(f'rank{i}.metric')} — standardised "
            f"separation {_ref(f'rank{i}.separation')}, {_ref(f'rank{i}.direction')} "
            f"in the first group."
        )
    lines.append(
        "This is associational. A high-ranking variable is not thereby a cause; use "
        "root cause analysis for mechanism."
    )
    return "\n".join(lines)


def _counterfactual(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    if bundle.slots.get("cf.verdict") and bundle.slots["cf.verdict"].value is None:
        return "The proposed change could not be evaluated."
    lines = [
        f"Applying the change across {_ref('cohort.n')} cycles is a "
        f"{_ref('cf.verdict')}: failures move from {_ref('before.any_mode')} to "
        f"{_ref('after.any_mode')}."
    ]
    lines.append(
        f"{_ref('cycles.rescued')} cycles stop failing while "
        f"{_ref('cycles.newly_failing')} begin to."
    )
    for mode in ("HDF", "PWF", "OSF"):
        if _has(bundle, f"before.{mode}"):
            lines.append(
                f"- {mode}: {_ref(f'before.{mode}')} to {_ref(f'after.{mode}')}."
            )
    return "\n".join(lines)


def _envelope(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    lines = [
        f"At {_ref('at.tool_wear')} of wear and {_ref('at.rotational_speed')}, on a "
        f"{_ref('at.product_type')} variant, the current setpoint is "
        f"{'safe' if bundle.slots['current.safe'].value == 'yes' else 'unsafe'} "
        f"({_ref('current.fired')})."
    ]
    if _has(bundle, "safe.torque_min", "safe.torque_max"):
        lines.append(
            f"Torque must sit between {_ref('safe.torque_min')} and "
            f"{_ref('safe.torque_max')}; the binding ceiling is "
            f"{_ref('safe.binding_ceiling')}."
        )
    if _has(bundle, "fix.action") and bundle.slots.get("fix.available", None) is not None:
        if bundle.slots["fix.available"].value == "yes":
            lines.append(
                f"Recommended change: {_ref('fix.action')} by {_ref('fix.delta')} to "
                f"{_ref('fix.new_value')}. That leaves power at "
                f"{_ref('fix.resulting_power')} and restores an overstrain margin of "
                f"{_ref('fix.resulting_overstrain_margin')}."
            )
            if _has(bundle, "fix.alternative_action"):
                lines.append(
                    f"Alternatively, {_ref('fix.alternative_action')} "
                    f"({_ref('fix.alternative_delta')})."
                )
    return "\n".join(lines)


def _forecast(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    lines = []
    status = bundle.slots.get("osf.status")
    if status is not None and status.value == "already exceeded":
        lines.append("This operating point has already crossed the overstrain limit.")
    elif _has(bundle, "osf.cycles_to_crossing"):
        lines.append(
            f"At {_ref('at.tool_wear')} of wear and {_ref('at.torque')}, overstrain is "
            f"reached in about {_ref('osf.cycles_to_crossing')} cycles "
            f"({_ref('osf.cycles_lower')} to {_ref('osf.cycles_upper')}), "
            f"a lead time of roughly {_ref('osf.lead_time_min')}."
        )
        lines.append(
            f"At this torque the limit corresponds to {_ref('osf.crossing_wear')} of wear."
        )
    if _has(bundle, "twf.cumulative_probability"):
        lines.append(
            f"Tool wear is already inside the replacement window: "
            f"{_ref('twf.per_cycle_probability')} per cycle, "
            f"{_ref('twf.cumulative_probability')} over the "
            f"{_ref('twf.cycles_left_in_window')} cycles remaining in the window. "
            "This mode is stochastic, so no crossing time can be given."
        )
    elif _has(bundle, "twf.cycles_to_window"):
        lines.append(
            f"The tool enters its replacement window in {_ref('twf.cycles_to_window')} "
            f"cycles ({_ref('twf.wear_to_window')} of wear)."
        )
    return "\n".join(lines)


def _records(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    return (
        f"{_ref('returned.count')} of {_ref('matched.count')} matching cycles are shown "
        f"below, of which {_ref('records.failures_in_set')} failed."
    )


def _data_quality(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    return "\n".join(
        [
            f"Across {_ref('dataset.rows')} cycles with {_ref('dataset.failures')} "
            f"failures, the verdict is: {_ref('verdict')}.",
            f"- {_ref('orphan_failures.count')} failures carry no documented mode.",
            f"- {_ref('rnf.flagged')} rows set the RNF flag but only "
            f"{_ref('rnf.also_machine_failure')} also set the failure label.",
            f"- The TWF column flags {_ref('twf.flagged')} rows against "
            f"{_ref('twf.window_rows')} inside the documented window, an in-window "
            f"rate of {_ref('twf.in_window_failure_rate')}.",
            f"- Knowledge base versus data: "
            f"{_ref('rule_audit.total_disagreements')} disagreements.",
        ]
    )


def _sql_explore(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    if bundle.slots.get("explore.status") and bundle.slots["explore.status"].value is None:
        return "The exploratory query was refused."
    return (
        f"The exploratory query returned {_ref('explore.rows')} rows across "
        f"{_ref('explore.columns')} columns."
    )


def _generic(plan: AnalysisPlan, bundle: EvidenceBundle) -> str:
    keys = list(bundle.slots)[:8]
    return "\n".join(f"- {k}: {_ref(k)}" for k in keys) or "No evidence produced."


_BY_OP = {
    OpName.DESCRIBE: _describe,
    OpName.RATE: _rate,
    OpName.COMPARE: _compare,
    OpName.ROOT_CAUSE: _root_cause,
    OpName.TREND: _trend,
    OpName.DRIVERS: _drivers,
    OpName.COUNTERFACTUAL: _counterfactual,
    OpName.ENVELOPE: _envelope,
    OpName.FORECAST: _forecast,
    OpName.RECORDS: _records,
    OpName.DATA_QUALITY: _data_quality,
    OpName.SQL_EXPLORE: _sql_explore,
}


def _label(metric: str) -> str:
    from copilot.knowledge import metric_label

    return metric_label(metric)


def format_answer(
    text: str, bundle: EvidenceBundle, *, scope: str = "", show_evidence: bool = False
) -> str:
    """Assemble the final response: scope, prose, non-critical caveats, provenance."""
    parts: list[str] = []
    if scope:
        parts.append(f"Scope: {scope}")
    parts.append(text)

    caveats = [w for w in bundle.warnings if w.severity is not Severity.CRITICAL]
    if caveats:
        parts.append("\n".join(f"Note: {w.message}" for w in caveats))

    if show_evidence:
        parts.append("Evidence\n" + bundle.evidence_table())

    p = bundle.provenance
    parts.append(
        f"[{p.op} · {p.row_count} rows · {p.elapsed_ms:.1f} ms · {p.tier} tier · "
        f"plan#{p.plan_hash} · kb@{p.kb_version} · data@{p.data_version}]"
    )
    return "\n\n".join(parts)
